<?php
declare (strict_types = 1);

namespace app\common\model;

use think\Collection;
use think\Model;

/**
 * @mixin \think\Model
 */
class Language extends BaseModel
{
    protected array $searchField = ['status'];

    protected string $selectField = 'code,name';

    public function getAll(array $where = []): Collection
    {
        $where['status'] = 1;
        return parent::getAll($where); // TODO: Change the autogenerated stub
    }
}
